name: Build macOS

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: build-macos-release

      - name: Install Qt
        uses: jurplel/install-qt-action@v3

      - name: Install other prerequisites
        run: |
          brew update
          brew install enchant openssl create-dmg --force-bottle

      - name: Configure CMake
        run: |
          cd '${{github.workspace}}'
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER_LAUNCHER=ccache ..

      - name: Build
        run: |
          cd '${{github.workspace}}'
          cd build
          cmake --build .

      - name: Install
        run: |
          cd '${{github.workspace}}'
          cd build
          cmake --install .

      - name: Detect version
        shell: bash
        run: |
          cd '${{github.workspace}}'
          kvi_version=$(grep -i "^set(VERSION_RELEASE .*)$" CMakeLists.txt | egrep -o '[0-9\.]' | tr -d '\n')
          git_desc=$(git describe --always)
          echo "dmg_name=KVIrc-$kvi_version-dev-$git_desc" >> "$GITHUB_ENV"

      - name: Create DMG
        shell: bash
        run: |
          cd '${{github.workspace}}'
          create-dmg --volname "${{ env.dmg_name }}" \
            --background "dist/macos/installer_background.png" \
            --window-pos 200 120 \
            --window-size 800 450 \
            --icon KVIrc.app 200 190 \
            --icon-size 100 \
            --app-drop-link 600 185 "${{ env.dmg_name }}.dmg" "build/KVIrc.app"

      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.dmg_name }}
          path: ${{ env.dmg_name }}.dmg

      - name: Upload to nightly
        shell: bash
        env:
          NIGHTLY_SFTP_KEY: ${{secrets.NIGHTLY_SFTP_KEY}}
        run: |
          brew install lftp
          echo "$NIGHTLY_SFTP_KEY" > ~/.ssh/id_rsa
          echo 'nightly.kvirc.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPWXPg8wxcaZqGLfFpS+TxkterxB4luo8e/bxh33poGQ' >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa ~/.ssh/known_hosts
          mkdir upload-area
          echo '{"bin": "${{ env.dmg_name }}.dmg", "size":' $(wc -c <"${{ env.dmg_name }}.dmg") '}' > upload-area/latest-macos
          mv *.dmg upload-area/
          lftp -c "connect -u ${{secrets.NIGHTLY_SFTP_USER}} sftp://nightly.kvirc.net; mirror -R upload-area x/"
